Hisilicon D03/D05: add SCSI cdb16 command
The D03/D05 SAS driver will fail to access disks beyond 2^32 sectors.
Symptoms can include the system entering grub rescue mode.
The issue log like this:

    error: file `/boot/grub/arm64-efi/normal.mod' not found.
    Entering rescue mode...
    grub rescue>

This is because the sas driver in uefi always use CDB10 SCSI command,
which is a 32 bit value, this command is used to read install data
from sectors, if the sector index higher than 2^32, for such data read,
the uefi sas driver previous will drop the higher bits.
The sector index is passed from LBA in Block IO protocol.
The sector size is 512 bytes, so when the HDD larger than 2TB will
trigger this issue.

This version we switch CDB16(64bit) mode for accessing sectors larger
than 2^32.

This commit resolves the issue:
https://bugs.linaro.org/show_bug.cgi?id=2393

Contributed-under: TianoCore Contribution Agreement 1.0
Signed-off-by: Chenhui Sun <sunchenhui@huawei.com>
Signed-off-by: Jason Zhang <zhangjinsong2@huawei.com>
Signed-off-by: Heyi Guo <heyi.guo@linaro.org>
Reviewed-by: Leif Lindholm <leif.lindholm@linaro.org>