Marvell/Armada8kPlus: Introduce ACPI support
This patch enables support for ACPI tables on Armada8kPlus
family. Its first user is Armada 8082 DB. Because of
iasl limitations, passing adderssess > 4GB cause
compilation errors, so enable only core functionalities
(SMP, GICv3, timer, etc.).

Change-Id: I3aacac0c3d101f84a110ffb1cca9d63c008bdb88
Contributed-under: TianoCore Contribution Agreement 1.1
Signed-off-by: Marcin Wojtas <mw@semihalf.com>
Reviewed-on: http://vgitil04.il.marvell.com:8080/52844
Tested-by: iSoC Platform CI <ykjenk@marvell.com>
Reviewed-by: Hua Jing <jinghua@marvell.com>