Marvell/Drivers: MvPca95xxDxe: Set default value to local variable
In RELEASE mode, PCA95xx driver fails compilation, due to local
variable might be used without initialzation value.
This patch fixes this compilation error.

Change-Id: I11cb3f5fb047c1ffafa1dc3624cf305db8263666
Contributed-under: TianoCore Contribution Agreement 1.1
Signed-off-by: jinghua <jinghua@marvell.com>
Reviewed-on: http://vgitil04.il.marvell.com:8080/52555
Tested-by: iSoC Platform CI <ykjenk@marvell.com>
Reviewed-by: Marcin Wojtas <mw@semihalf.com>